// ============================================================================
// Contoso Construction — RFP Response Builder — Sample Data
// ============================================================================

const projects = [
  {
    id: "PRJ-2026-001",
    name: "Golden Gate Connector Bridge – Phase II",
    client: "Bay Area Transit Authority",
    location: "San Francisco, CA",
    sector: "Infrastructure – Bridges",
    estimatedValue: "$485,000,000",
    rfpDeadline: "2026-04-15",
    dateCreated: "2026-01-18",
    bidManager: "Sarah Mitchell",
    status: "In Progress",
    description:
      "Design-build of a 1.2-mile cable-stayed bridge connecting the northern waterfront district to the downtown transit hub. Includes seismic retrofit of existing piers, marine foundation work, and a multi-use pedestrian/cycling pathway.",
    documents: [
      { id: "DOC-001", name: "RFP_GoldenGateConnector_Full.pdf", type: "pdf", size: "12.4 MB", uploaded: "2026-01-20", uploadedBy: "Sarah Mitchell" },
      { id: "DOC-002", name: "Geotech_Report_Phase1.pdf", type: "pdf", size: "8.7 MB", uploaded: "2026-01-21", uploadedBy: "James Thornton" },
      { id: "DOC-003", name: "Cost_Estimate_Preliminary.xlsx", type: "excel", size: "2.1 MB", uploaded: "2026-01-22", uploadedBy: "Maria Chen" },
      { id: "DOC-004", name: "Structural_Drawings_Rev_A.pdf", type: "pdf", size: "45.3 MB", uploaded: "2026-01-25", uploadedBy: "David Okonkwo" },
      { id: "DOC-005", name: "Client_Clarifications_Jan26.eml", type: "email", size: "340 KB", uploaded: "2026-01-26", uploadedBy: "Sarah Mitchell" },
      { id: "DOC-006", name: "Environmental_Impact_Assessment.pdf", type: "pdf", size: "6.9 MB", uploaded: "2026-01-28", uploadedBy: "Lisa Park" },
      { id: "DOC-007", name: "BOQ_Bridge_Substructure.xlsx", type: "excel", size: "1.8 MB", uploaded: "2026-02-01", uploadedBy: "Maria Chen" },
      { id: "DOC-008", name: "RE_Schedule_Discussion.eml", type: "email", size: "220 KB", uploaded: "2026-02-03", uploadedBy: "James Thornton" },
      { id: "DOC-009", name: "Traffic_Management_Plan.pdf", type: "pdf", size: "3.5 MB", uploaded: "2026-02-05", uploadedBy: "Robert Nakamura" },
      { id: "DOC-010", name: "Insurance_Requirements_Summary.xlsx", type: "excel", size: "890 KB", uploaded: "2026-02-07", uploadedBy: "Sarah Mitchell" },
    ],
    pastProjects: [
      { id: "PP-101", name: "Chesapeake Bay Bridge Rehabilitation", value: "$320M", year: 2024, matchScore: 94, relevance: "Similar cable-stayed design, marine foundation, seismic retrofit" },
      { id: "PP-102", name: "Hudson River Pedestrian Crossing", value: "$210M", year: 2023, matchScore: 89, relevance: "Multi-use bridge, urban waterfront, complex stakeholder management" },
      { id: "PP-103", name: "I-405 Interchange Reconstruction", value: "$175M", year: 2022, matchScore: 82, relevance: "Heavy civil infrastructure, traffic management, phased construction" },
      { id: "PP-104", name: "Port of Long Beach Access Bridge", value: "$290M", year: 2023, matchScore: 78, relevance: "Marine construction, deep foundation piling, environmental compliance" },
      { id: "PP-105", name: "Mississippi River Rail Bridge Upgrade", value: "$145M", year: 2021, matchScore: 73, relevance: "Bridge rehabilitation, steel superstructure, navigable waterway work" },
    ],
  },
  {
    id: "PRJ-2026-002",
    name: "MetroStar Arena & Convention Center",
    client: "City of Austin Development Corp.",
    location: "Austin, TX",
    sector: "Commercial – Stadiums & Venues",
    estimatedValue: "$1,200,000,000",
    rfpDeadline: "2026-05-30",
    dateCreated: "2026-02-05",
    bidManager: "James Thornton",
    status: "In Progress",
    description:
      "Construction of a 65,000-seat retractable-roof stadium with an adjoining 250,000 sq ft convention center. The project includes extensive site preparation, underground parking for 5,000 vehicles, and LEED Platinum certification targets.",
    documents: [
      { id: "DOC-101", name: "RFP_MetroStar_Arena_Complete.pdf", type: "pdf", size: "28.5 MB", uploaded: "2026-02-06", uploadedBy: "James Thornton" },
      { id: "DOC-102", name: "Architectural_Concept_Design.pdf", type: "pdf", size: "67.2 MB", uploaded: "2026-02-07", uploadedBy: "David Okonkwo" },
      { id: "DOC-103", name: "MEP_Specifications_Draft.pdf", type: "pdf", size: "15.8 MB", uploaded: "2026-02-08", uploadedBy: "Lisa Park" },
      { id: "DOC-104", name: "Budget_Breakdown_Structure.xlsx", type: "excel", size: "4.3 MB", uploaded: "2026-02-10", uploadedBy: "Maria Chen" },
      { id: "DOC-105", name: "RE_Sustainability_Requirements.eml", type: "email", size: "180 KB", uploaded: "2026-02-11", uploadedBy: "James Thornton" },
      { id: "DOC-106", name: "Soil_Investigation_Report.pdf", type: "pdf", size: "9.1 MB", uploaded: "2026-02-12", uploadedBy: "Robert Nakamura" },
      { id: "DOC-107", name: "Stakeholder_Meeting_Notes.eml", type: "email", size: "95 KB", uploaded: "2026-02-13", uploadedBy: "Sarah Mitchell" },
      { id: "DOC-108", name: "Steel_Tonnage_Estimate.xlsx", type: "excel", size: "1.2 MB", uploaded: "2026-02-14", uploadedBy: "Maria Chen" },
      { id: "DOC-109", name: "Fire_Safety_Compliance_Review.pdf", type: "pdf", size: "5.6 MB", uploaded: "2026-02-16", uploadedBy: "Lisa Park" },
      { id: "DOC-110", name: "Retractable_Roof_Mechanism_Spec.pdf", type: "pdf", size: "11.4 MB", uploaded: "2026-02-18", uploadedBy: "David Okonkwo" },
    ],
    pastProjects: [
      { id: "PP-201", name: "SolarDome Stadium – Phoenix", value: "$950M", year: 2024, matchScore: 96, relevance: "Retractable roof stadium, 60k seats, LEED Gold, underground parking" },
      { id: "PP-202", name: "National Convention Center – Denver", value: "$480M", year: 2023, matchScore: 91, relevance: "Large-scale convention facility, complex MEP, public space integration" },
      { id: "PP-203", name: "Riverside Entertainment District", value: "$720M", year: 2022, matchScore: 85, relevance: "Mixed-use entertainment, large site, phased delivery" },
      { id: "PP-204", name: "Olympic Aquatics Center – LA", value: "$340M", year: 2024, matchScore: 80, relevance: "Specialty sports venue, retractable elements, sustainability focus" },
      { id: "PP-205", name: "Grand Prairie Multiplex Arena", value: "$280M", year: 2021, matchScore: 76, relevance: "Arena construction, Texas market, fast-track delivery" },
    ],
  },
  {
    id: "PRJ-2026-003",
    name: "Skyline Tower – Mixed-Use High Rise",
    client: "Pacific Rim Developments",
    location: "Seattle, WA",
    sector: "Commercial – High Rise",
    estimatedValue: "$650,000,000",
    rfpDeadline: "2026-06-20",
    dateCreated: "2026-02-12",
    bidManager: "Maria Chen",
    status: "In Progress",
    description:
      "A 72-story mixed-use supertall tower featuring 400 luxury residential units, 350,000 sq ft of Class A office space, a 200-key boutique hotel, and ground-level retail. Includes a sky-bridge connection to the adjacent transit terminal and a 6-level underground parking structure.",
    documents: [
      { id: "DOC-201", name: "RFP_Skyline_Tower_Package.pdf", type: "pdf", size: "34.1 MB", uploaded: "2026-02-13", uploadedBy: "Maria Chen" },
      { id: "DOC-202", name: "Wind_Tunnel_Analysis_Report.pdf", type: "pdf", size: "18.7 MB", uploaded: "2026-02-14", uploadedBy: "David Okonkwo" },
      { id: "DOC-203", name: "Foundation_Design_Options.xlsx", type: "excel", size: "3.6 MB", uploaded: "2026-02-15", uploadedBy: "James Thornton" },
      { id: "DOC-204", name: "Facade_Engineering_Concepts.pdf", type: "pdf", size: "22.3 MB", uploaded: "2026-02-16", uploadedBy: "Lisa Park" },
      { id: "DOC-205", name: "RE_Zoning_Variance_Approval.eml", type: "email", size: "410 KB", uploaded: "2026-02-17", uploadedBy: "Sarah Mitchell" },
      { id: "DOC-206", name: "Vertical_Transportation_Study.pdf", type: "pdf", size: "7.4 MB", uploaded: "2026-02-18", uploadedBy: "Robert Nakamura" },
      { id: "DOC-207", name: "Concrete_Mix_Design_Specs.pdf", type: "pdf", size: "4.8 MB", uploaded: "2026-02-19", uploadedBy: "James Thornton" },
      { id: "DOC-208", name: "RE_Client_Design_Preferences.eml", type: "email", size: "275 KB", uploaded: "2026-02-20", uploadedBy: "Maria Chen" },
      { id: "DOC-209", name: "Cost_Model_Scenario_Analysis.xlsx", type: "excel", size: "5.2 MB", uploaded: "2026-02-21", uploadedBy: "Maria Chen" },
      { id: "DOC-210", name: "Mechanical_Plant_Room_Layout.pdf", type: "pdf", size: "9.8 MB", uploaded: "2026-02-22", uploadedBy: "Lisa Park" },
    ],
    pastProjects: [
      { id: "PP-301", name: "Apex Tower – 68 Stories, Chicago", value: "$580M", year: 2024, matchScore: 97, relevance: "Supertall mixed-use, complex foundation, curtain wall facade" },
      { id: "PP-302", name: "Harbor Point Residential Tower", value: "$420M", year: 2023, matchScore: 90, relevance: "High-rise residential, luxury finishes, sky-bridge connectivity" },
      { id: "PP-303", name: "One Pacific Place – Office Tower", value: "$310M", year: 2022, matchScore: 86, relevance: "Class A office high-rise, Seattle market, transit-oriented" },
      { id: "PP-304", name: "Crown Hotel & Residences – Miami", value: "$490M", year: 2024, matchScore: 83, relevance: "Mixed-use hotel/residential, premium materials, podium parking" },
      { id: "PP-305", name: "Meridian Supertall – New York", value: "$780M", year: 2023, matchScore: 79, relevance: "Supertall construction, wind engineering, vertical logistics" },
    ],
  },
  {
    id: "PRJ-2026-004",
    name: "Interstate 90 Corridor Expansion",
    client: "Washington State DOT",
    location: "Bellevue to Spokane, WA",
    sector: "Infrastructure – Highway",
    estimatedValue: "$2,100,000,000",
    rfpDeadline: "2026-07-31",
    dateCreated: "2026-02-20",
    bidManager: "Robert Nakamura",
    status: "Draft",
    description:
      "Multi-phase highway expansion adding two lanes in each direction across a 180-mile corridor. Includes 14 bridge replacements, 8 new interchange constructions, stormwater management systems, and intelligent transportation system (ITS) infrastructure upgrades.",
    documents: [
      { id: "DOC-301", name: "RFP_I90_Corridor_Volume1.pdf", type: "pdf", size: "52.0 MB", uploaded: "2026-02-21", uploadedBy: "Robert Nakamura" },
      { id: "DOC-302", name: "Pavement_Design_Report.pdf", type: "pdf", size: "14.2 MB", uploaded: "2026-02-21", uploadedBy: "James Thornton" },
      { id: "DOC-303", name: "Bridge_Inventory_Assessment.xlsx", type: "excel", size: "6.7 MB", uploaded: "2026-02-22", uploadedBy: "David Okonkwo" },
      { id: "DOC-304", name: "ITS_Infrastructure_Requirements.pdf", type: "pdf", size: "8.9 MB", uploaded: "2026-02-22", uploadedBy: "Lisa Park" },
      { id: "DOC-305", name: "RE_Federal_Funding_Compliance.eml", type: "email", size: "520 KB", uploaded: "2026-02-23", uploadedBy: "Robert Nakamura" },
      { id: "DOC-306", name: "Environmental_Clearance_Phase1.pdf", type: "pdf", size: "11.3 MB", uploaded: "2026-02-23", uploadedBy: "Sarah Mitchell" },
      { id: "DOC-307", name: "ROW_Acquisition_Schedule.xlsx", type: "excel", size: "2.4 MB", uploaded: "2026-02-24", uploadedBy: "Maria Chen" },
      { id: "DOC-308", name: "RE_Public_Hearing_Summary.eml", type: "email", size: "310 KB", uploaded: "2026-02-24", uploadedBy: "Robert Nakamura" },
      { id: "DOC-309", name: "Drainage_Design_Criteria.pdf", type: "pdf", size: "5.7 MB", uploaded: "2026-02-24", uploadedBy: "James Thornton" },
      { id: "DOC-310", name: "Preliminary_CPM_Schedule.xlsx", type: "excel", size: "3.9 MB", uploaded: "2026-02-25", uploadedBy: "Maria Chen" },
    ],
    pastProjects: [
      { id: "PP-401", name: "I-5 Corridor Modernization – Oregon", value: "$1.8B", year: 2024, matchScore: 95, relevance: "Large-scale highway expansion, bridge replacements, ITS systems" },
      { id: "PP-402", name: "Texas SH-130 Tollway Extension", value: "$1.2B", year: 2023, matchScore: 88, relevance: "Multi-phase highway, interchange construction, phased delivery" },
      { id: "PP-403", name: "I-75 Bridge Replacement Program", value: "$640M", year: 2022, matchScore: 84, relevance: "Multiple bridge replacements, DOT compliance, traffic management" },
      { id: "PP-404", name: "Colorado Mountain Corridor Upgrade", value: "$920M", year: 2023, matchScore: 81, relevance: "Mountain highway, challenging terrain, environmental sensitivity" },
      { id: "PP-405", name: "Florida Turnpike Widening – Phase III", value: "$550M", year: 2021, matchScore: 75, relevance: "Lane additions, ITS upgrades, stormwater management" },
    ],
  },
];

// ============================================================================
// Staffing Data — Construction Industry Roles & Personnel
// ============================================================================

const staffingRoles = {
  "PRJ-2026-001": [
    {
      role: "Project Director",
      description: "Provides executive-level oversight of all project phases, manages client relationships, and ensures delivery within contractual obligations.",
      candidates: [
        {
          id: "EMP-001",
          name: "Richard Hargrove, PE, PMP",
          location: "United States",
          linkedin: "https://linkedin.com/in/richard-hargrove",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/RHargrove_CV.pdf",
          matchScore: 96,
          locked: false,
          skills: "30+ years leading large-scale infrastructure projects exceeding $500M. Expert in design-build delivery, stakeholder management, and regulatory compliance. Certified PMP and licensed PE in 12 states. Proven track record in bridge and marine construction with DOT agencies nationwide.",
          pastProjects: ["Chesapeake Bay Bridge Rehabilitation", "I-5 Corridor Modernization", "Hudson River Pedestrian Crossing"],
        },
        {
          id: "EMP-002",
          name: "Catherine Dupont, MSc, CEng",
          location: "Canada",
          linkedin: "https://linkedin.com/in/catherine-dupont",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/CDupont_CV.pdf",
          matchScore: 88,
          locked: false,
          skills: "25 years of project leadership in heavy civil and transportation infrastructure across North America. Specializes in P3 delivery models, risk management, and multi-disciplinary team coordination. Chartered Engineer with deep experience in cable-stayed and suspension bridge projects.",
          pastProjects: ["Port of Long Beach Access Bridge", "Mississippi River Rail Bridge Upgrade", "Colorado Mountain Corridor Upgrade"],
        },
      ],
    },
    {
      role: "Lead Structural Engineer",
      description: "Leads all structural design and analysis activities, ensures code compliance, and oversees structural steel and concrete works.",
      candidates: [
        {
          id: "EMP-003",
          name: "Dr. Akira Tanaka, PhD, SE",
          location: "Japan",
          linkedin: "https://linkedin.com/in/akira-tanaka-se",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/ATanaka_CV.pdf",
          matchScore: 97,
          locked: false,
          skills: "Structural engineering specialist with 20 years of experience in long-span bridge design and seismic analysis. PhD in Structural Dynamics from Tokyo University. Licensed SE in California and Washington. Published researcher in cable-stayed bridge aerodynamics and progressive collapse resistance.",
          pastProjects: ["Chesapeake Bay Bridge Rehabilitation", "Apex Tower – 68 Stories", "Meridian Supertall – New York"],
        },
        {
          id: "EMP-004",
          name: "Elena Vasquez, PE, MSc",
          location: "United States",
          linkedin: "https://linkedin.com/in/elena-vasquez-pe",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/EVasquez_CV.pdf",
          matchScore: 91,
          locked: false,
          skills: "18 years designing complex bridge structures including post-tensioned concrete, steel truss, and cable-stayed systems. Expert in finite element analysis (FEA), AASHTO LRFD bridge design, and construction-stage analysis. Strong background in seismic retrofitting and accelerated bridge construction (ABC) techniques.",
          pastProjects: ["Hudson River Pedestrian Crossing", "I-75 Bridge Replacement Program", "Port of Long Beach Access Bridge"],
        },
        {
          id: "EMP-005",
          name: "Marcus Webb, PE",
          location: "United Kingdom",
          linkedin: "https://linkedin.com/in/marcus-webb-pe",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/MWebb_CV.pdf",
          matchScore: 85,
          locked: false,
          skills: "15 years in structural engineering with international bridge and marine structure experience. Proficient in SAP2000, LUSAS, and MIDAS Civil software. Experienced in value engineering, construction methodology reviews, and independent design checks for transportation authorities across the UK and US.",
          pastProjects: ["Mississippi River Rail Bridge Upgrade", "Texas SH-130 Tollway Extension"],
        },
      ],
    },
    {
      role: "Construction Manager",
      description: "Manages day-to-day construction operations, coordinates subcontractors, and ensures adherence to schedule, budget, and safety standards.",
      candidates: [
        {
          id: "EMP-006",
          name: "Frank O'Sullivan, CCM",
          location: "United States",
          linkedin: "https://linkedin.com/in/frank-osullivan",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/FOSullivan_CV.pdf",
          matchScore: 93,
          locked: false,
          skills: "22 years managing construction operations on infrastructure projects ranging from $50M to $800M. Certified Construction Manager (CCM) with expertise in CPM scheduling, earned value management, and lean construction principles. Extensive marine and over-water construction experience with zero lost-time incident record on last 5 projects.",
          pastProjects: ["Chesapeake Bay Bridge Rehabilitation", "I-405 Interchange Reconstruction", "Florida Turnpike Widening"],
        },
        {
          id: "EMP-007",
          name: "Priya Sharma, PMP",
          location: "India",
          linkedin: "https://linkedin.com/in/priya-sharma-cm",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/PSharma_CV.pdf",
          matchScore: 86,
          locked: false,
          skills: "16 years of construction management experience on large-scale bridge, highway, and tunnel projects. Strong capabilities in BIM coordination (Navisworks, Revit), 4D scheduling, and quality assurance/quality control (QA/QC). Known for implementing digital construction monitoring systems that reduce rework by up to 30%.",
          pastProjects: ["Port of Long Beach Access Bridge", "Texas SH-130 Tollway Extension", "Hudson River Pedestrian Crossing"],
        },
      ],
    },
    {
      role: "Geotechnical Engineer",
      description: "Leads subsurface investigations, foundation design, and ground improvement recommendations for all structural elements.",
      candidates: [
        {
          id: "EMP-008",
          name: "Dr. Samuel Osei, PhD, PE",
          location: "Ghana",
          linkedin: "https://linkedin.com/in/samuel-osei-geotech",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/SOsei_CV.pdf",
          matchScore: 94,
          locked: false,
          skills: "Expert geotechnical engineer with 19 years specializing in deep foundation design, marine geotechnics, and ground improvement techniques. PhD in Geotechnical Engineering from MIT. Proficient in PLAXIS 3D, GeoStudio, and LPILE. Experienced with drilled shafts, driven piles, and cofferdam design for bridge foundations in challenging soil and marine conditions.",
          pastProjects: ["Port of Long Beach Access Bridge", "Chesapeake Bay Bridge Rehabilitation", "Apex Tower – 68 Stories"],
        },
        {
          id: "EMP-009",
          name: "Hannah Johansson, MSc",
          location: "Sweden",
          linkedin: "https://linkedin.com/in/hannah-johansson-geo",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/HJohansson_CV.pdf",
          matchScore: 82,
          locked: false,
          skills: "14 years of geotechnical engineering experience across Scandinavia and North America. Specializes in soft soil improvement, slope stability analysis, and instrumentation monitoring programs. Skilled in finite element geotechnical modeling, liquefaction assessment, and probabilistic foundation design for transportation infrastructure.",
          pastProjects: ["Colorado Mountain Corridor Upgrade", "I-75 Bridge Replacement Program"],
        },
      ],
    },
    {
      role: "Environmental Compliance Manager",
      description: "Ensures all construction activities meet environmental regulations, manages permits, and coordinates with regulatory agencies.",
      candidates: [
        {
          id: "EMP-010",
          name: "Dr. Maria Santos, ENV SP",
          location: "Brazil",
          linkedin: "https://linkedin.com/in/maria-santos-env",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/MSantos_CV.pdf",
          matchScore: 90,
          locked: false,
          skills: "17 years in environmental compliance and sustainability for major infrastructure projects. Envision Sustainability Professional (ENV SP) with expertise in NEPA/CEQA compliance, wetland mitigation, endangered species management, and stormwater pollution prevention (SWPPP). Experienced in securing Section 404/401 permits for marine and waterway construction projects.",
          pastProjects: ["Chesapeake Bay Bridge Rehabilitation", "Hudson River Pedestrian Crossing", "I-5 Corridor Modernization"],
        },
      ],
    },
    {
      role: "Cost Estimator / Quantity Surveyor",
      description: "Develops detailed cost estimates, manages bills of quantities, and provides cost control and value engineering analysis.",
      candidates: [
        {
          id: "EMP-011",
          name: "Trevor McAllister, CCP, MRICS",
          location: "Australia",
          linkedin: "https://linkedin.com/in/trevor-mcallister-qs",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/TMcAllister_CV.pdf",
          matchScore: 92,
          locked: false,
          skills: "21 years as a cost estimator and quantity surveyor on heavy civil and infrastructure projects. Certified Cost Professional (CCP) and MRICS-qualified. Expert in parametric and detailed bottom-up estimating, risk-adjusted contingency modeling, and earned value analysis (EVA). Proficient in CostX, Candy, and HeavyBid estimating platforms.",
          pastProjects: ["I-5 Corridor Modernization", "Port of Long Beach Access Bridge", "SolarDome Stadium – Phoenix"],
        },
      ],
    },
    {
      role: "Health & Safety Director",
      description: "Develops and enforces site-wide health and safety programs, ensures OSHA compliance, and manages incident prevention strategies.",
      candidates: [
        {
          id: "EMP-012",
          name: "Karen Whitfield, CSP, CHST",
          location: "United States",
          linkedin: "https://linkedin.com/in/karen-whitfield-safety",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/KWhitfield_CV.pdf",
          matchScore: 91,
          locked: false,
          skills: "18 years directing safety programs on major construction projects with a career EMR of 0.68. Certified Safety Professional (CSP) and Construction Health & Safety Technician (CHST). Expert in behavior-based safety (BBS), fall protection planning, confined space rescue, and marine construction safety. Led safety teams on projects achieving 5M+ person-hours with zero lost-time incidents.",
          pastProjects: ["Chesapeake Bay Bridge Rehabilitation", "I-405 Interchange Reconstruction", "Hudson River Pedestrian Crossing"],
        },
      ],
    },
    {
      role: "Lead Scheduler / Planning Engineer",
      description: "Develops and maintains the CPM schedule, performs schedule risk analysis, and tracks progress against baseline milestones.",
      candidates: [
        {
          id: "EMP-013",
          name: "Jean-Pierre Moreau, PSP",
          location: "France",
          linkedin: "https://linkedin.com/in/jp-moreau-planning",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/JPMoreau_CV.pdf",
          matchScore: 89,
          locked: false,
          skills: "16 years as a planning and scheduling specialist on mega-projects valued up to $2B. Planning & Scheduling Professional (PSP) certified by AACE. Expert in Primavera P6, schedule risk analysis (SRA) using @RISK, and forensic delay analysis (as-built vs as-planned). Known for developing robust baseline schedules with resource-loaded logic on bridge and highway projects.",
          pastProjects: ["I-5 Corridor Modernization", "Texas SH-130 Tollway Extension", "Mississippi River Rail Bridge Upgrade"],
        },
      ],
    },
  ],
  "PRJ-2026-002": [
    {
      role: "Project Director",
      description: "Provides executive-level oversight, manages the client relationship with the City, and ensures the project meets scope, schedule, and budget targets.",
      candidates: [
        {
          id: "EMP-014",
          name: "William Torres, PE, DBIA",
          location: "United States",
          linkedin: "https://linkedin.com/in/william-torres-dbia",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/WTorres_CV.pdf",
          matchScore: 95,
          locked: false,
          skills: "28 years leading stadium, arena, and large-venue construction projects. Design-Build Institute of America (DBIA) certified with PE licensure in 8 states. Expert in GMP contract delivery, retractable roof systems, and fast-track scheduling. Successfully delivered three 50k+ seat stadiums on time and under budget.",
          pastProjects: ["SolarDome Stadium – Phoenix", "Grand Prairie Multiplex Arena", "Olympic Aquatics Center – LA"],
        },
        {
          id: "EMP-001",
          name: "Richard Hargrove, PE, PMP",
          location: "United States",
          linkedin: "https://linkedin.com/in/richard-hargrove",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/RHargrove_CV.pdf",
          matchScore: 82,
          locked: false,
          skills: "30+ years leading large-scale infrastructure projects exceeding $500M. Expert in design-build delivery, stakeholder management, and regulatory compliance. Certified PMP and licensed PE in 12 states. Proven track record in bridge and marine construction with DOT agencies nationwide.",
          pastProjects: ["Chesapeake Bay Bridge Rehabilitation", "I-5 Corridor Modernization", "Hudson River Pedestrian Crossing"],
        },
      ],
    },
    {
      role: "Lead Architect",
      description: "Directs architectural design development, coordinates with engineering disciplines, and manages design quality throughout all phases.",
      candidates: [
        {
          id: "EMP-015",
          name: "Isabella Romano, AIA, LEED AP",
          location: "Italy",
          linkedin: "https://linkedin.com/in/isabella-romano-architect",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/IRomano_CV.pdf",
          matchScore: 94,
          locked: false,
          skills: "22 years of architectural practice specializing in sports venues, performance halls, and large public assembly spaces. AIA member and LEED AP BD+C certified. Expert in parametric design (Grasshopper/Rhino), stadium sightline optimization, and acoustic performance. Award-winning design portfolio with three AIA Honor Awards for public architecture.",
          pastProjects: ["SolarDome Stadium – Phoenix", "National Convention Center – Denver", "Olympic Aquatics Center – LA"],
        },
      ],
    },
    {
      role: "Lead Structural Engineer",
      description: "Leads structural design for the stadium superstructure, retractable roof, and convention center long-span elements.",
      candidates: [
        {
          id: "EMP-003",
          name: "Dr. Akira Tanaka, PhD, SE",
          location: "Japan",
          linkedin: "https://linkedin.com/in/akira-tanaka-se",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/ATanaka_CV.pdf",
          matchScore: 93,
          locked: false,
          skills: "Structural engineering specialist with 20 years of experience in long-span bridge design and seismic analysis. PhD in Structural Dynamics from Tokyo University. Licensed SE in California and Washington. Published researcher in cable-stayed bridge aerodynamics and progressive collapse resistance.",
          pastProjects: ["Chesapeake Bay Bridge Rehabilitation", "Apex Tower – 68 Stories", "Meridian Supertall – New York"],
        },
        {
          id: "EMP-016",
          name: "Omar Al-Rashid, MSc, PE",
          location: "UAE",
          linkedin: "https://linkedin.com/in/omar-al-rashid-str",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/OAlRashid_CV.pdf",
          matchScore: 88,
          locked: false,
          skills: "17 years designing long-span roof structures, retractable systems, and stadium superstructures. Expert in tension fabric, ETFE cladding, and kinetic architecture engineering. Proficient in ETABS, SAP2000, and Tekla Structures. Delivered structural design for three FIFA-standard stadiums in the Middle East.",
          pastProjects: ["SolarDome Stadium – Phoenix", "Riverside Entertainment District", "Grand Prairie Multiplex Arena"],
        },
      ],
    },
    {
      role: "MEP Engineering Lead",
      description: "Coordinates all mechanical, electrical, and plumbing systems design and ensures integration with architectural and structural elements.",
      candidates: [
        {
          id: "EMP-017",
          name: "Linda Chen-Williams, PE, CxA",
          location: "United States",
          linkedin: "https://linkedin.com/in/linda-chen-williams",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/LChenWilliams_CV.pdf",
          matchScore: 92,
          locked: false,
          skills: "20 years leading MEP design on large commercial, stadium, and convention center projects. Certified Commissioning Authority (CxA) and PE. Expert in large-venue HVAC systems, electrical distribution for events, and LEED-compliant mechanical design. Skilled in energy modeling (eQUEST, IES VE) and building performance optimization.",
          pastProjects: ["SolarDome Stadium – Phoenix", "National Convention Center – Denver", "Crown Hotel & Residences – Miami"],
        },
      ],
    },
    {
      role: "Construction Manager",
      description: "Oversees all construction activities, manages trade contractors, and drives schedule performance on the stadium and convention center builds.",
      candidates: [
        {
          id: "EMP-006",
          name: "Frank O'Sullivan, CCM",
          location: "United States",
          linkedin: "https://linkedin.com/in/frank-osullivan",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/FOSullivan_CV.pdf",
          matchScore: 90,
          locked: false,
          skills: "22 years managing construction operations on infrastructure projects ranging from $50M to $800M. Certified Construction Manager (CCM) with expertise in CPM scheduling, earned value management, and lean construction principles. Extensive marine and over-water construction experience with zero lost-time incident record on last 5 projects.",
          pastProjects: ["Chesapeake Bay Bridge Rehabilitation", "I-405 Interchange Reconstruction", "Florida Turnpike Widening"],
        },
        {
          id: "EMP-018",
          name: "Carlos Mendoza, CCM, LEED AP",
          location: "Mexico",
          linkedin: "https://linkedin.com/in/carlos-mendoza-ccm",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/CMendoza_CV.pdf",
          matchScore: 85,
          locked: false,
          skills: "19 years in construction management with a focus on large-scale commercial and entertainment venues. CCM-certified with LEED AP credential. Experienced in managing 500+ person field crews, concrete frame construction, and curtain wall installation. Delivered three stadium projects with combined value exceeding $1.5B across the Americas.",
          pastProjects: ["Grand Prairie Multiplex Arena", "Riverside Entertainment District", "National Convention Center – Denver"],
        },
      ],
    },
    {
      role: "Sustainability & LEED Consultant",
      description: "Manages the LEED Platinum certification process, advises on sustainable design strategies, and tracks environmental performance metrics.",
      candidates: [
        {
          id: "EMP-019",
          name: "Dr. Annika Berg, ENV SP, LEED Fellow",
          location: "Germany",
          linkedin: "https://linkedin.com/in/annika-berg-sustainability",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/ABerg_CV.pdf",
          matchScore: 96,
          locked: false,
          skills: "15 years dedicated to sustainable construction and green building certification. One of fewer than 100 LEED Fellows globally with Envision SP certification. Expert in whole-life carbon assessment, renewable energy integration, and circular economy principles in construction. Successfully led LEED Platinum certification on six major projects including two stadiums.",
          pastProjects: ["SolarDome Stadium – Phoenix", "Olympic Aquatics Center – LA", "National Convention Center – Denver"],
        },
      ],
    },
    {
      role: "Cost Estimator / Quantity Surveyor",
      description: "Prepares and manages cost plans, bills of quantities, and change order evaluations for the stadium and convention center.",
      candidates: [
        {
          id: "EMP-011",
          name: "Trevor McAllister, CCP, MRICS",
          location: "Australia",
          linkedin: "https://linkedin.com/in/trevor-mcallister-qs",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/TMcAllister_CV.pdf",
          matchScore: 94,
          locked: false,
          skills: "21 years as a cost estimator and quantity surveyor on heavy civil and infrastructure projects. Certified Cost Professional (CCP) and MRICS-qualified. Expert in parametric and detailed bottom-up estimating, risk-adjusted contingency modeling, and earned value analysis (EVA). Proficient in CostX, Candy, and HeavyBid estimating platforms.",
          pastProjects: ["I-5 Corridor Modernization", "Port of Long Beach Access Bridge", "SolarDome Stadium – Phoenix"],
        },
      ],
    },
    {
      role: "Health & Safety Director",
      description: "Develops comprehensive HSE programs for the stadium construction environment, including working at height, heavy lift, and public safety protocols.",
      candidates: [
        {
          id: "EMP-012",
          name: "Karen Whitfield, CSP, CHST",
          location: "United States",
          linkedin: "https://linkedin.com/in/karen-whitfield-safety",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/KWhitfield_CV.pdf",
          matchScore: 89,
          locked: false,
          skills: "18 years directing safety programs on major construction projects with a career EMR of 0.68. Certified Safety Professional (CSP) and Construction Health & Safety Technician (CHST). Expert in behavior-based safety (BBS), fall protection planning, confined space rescue, and marine construction safety.",
          pastProjects: ["Chesapeake Bay Bridge Rehabilitation", "I-405 Interchange Reconstruction", "Hudson River Pedestrian Crossing"],
        },
      ],
    },
  ],
  "PRJ-2026-003": [
    {
      role: "Project Director",
      description: "Provides executive leadership for the supertall tower program, manages the developer relationship, and ensures integrated delivery across all building uses.",
      candidates: [
        {
          id: "EMP-001",
          name: "Richard Hargrove, PE, PMP",
          location: "United States",
          linkedin: "https://linkedin.com/in/richard-hargrove",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/RHargrove_CV.pdf",
          matchScore: 91,
          locked: false,
          skills: "30+ years leading large-scale infrastructure projects exceeding $500M. Expert in design-build delivery, stakeholder management, and regulatory compliance. Certified PMP and licensed PE in 12 states. Proven track record in bridge and marine construction with DOT agencies nationwide.",
          pastProjects: ["Chesapeake Bay Bridge Rehabilitation", "I-5 Corridor Modernization", "Hudson River Pedestrian Crossing"],
        },
        {
          id: "EMP-002",
          name: "Catherine Dupont, MSc, CEng",
          location: "Canada",
          linkedin: "https://linkedin.com/in/catherine-dupont",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/CDupont_CV.pdf",
          matchScore: 85,
          locked: false,
          skills: "25 years of project leadership in heavy civil and transportation infrastructure across North America. Specializes in P3 delivery models, risk management, and multi-disciplinary team coordination. Chartered Engineer with deep experience in cable-stayed and suspension bridge projects.",
          pastProjects: ["Port of Long Beach Access Bridge", "Mississippi River Rail Bridge Upgrade", "Colorado Mountain Corridor Upgrade"],
        },
      ],
    },
    {
      role: "Lead Structural Engineer",
      description: "Leads the structural design of the 72-story tower including the lateral system, foundation, and sky-bridge connection.",
      candidates: [
        {
          id: "EMP-003",
          name: "Dr. Akira Tanaka, PhD, SE",
          location: "Japan",
          linkedin: "https://linkedin.com/in/akira-tanaka-se",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/ATanaka_CV.pdf",
          matchScore: 98,
          locked: false,
          skills: "Structural engineering specialist with 20 years of experience in long-span bridge design and seismic analysis. PhD in Structural Dynamics from Tokyo University. Licensed SE in California and Washington. Published researcher in cable-stayed bridge aerodynamics and progressive collapse resistance.",
          pastProjects: ["Chesapeake Bay Bridge Rehabilitation", "Apex Tower – 68 Stories", "Meridian Supertall – New York"],
        },
      ],
    },
    {
      role: "Facade Engineering Lead",
      description: "Designs and manages the unitized curtain wall system, coordinates with architects on aesthetic performance, and ensures weather-tightness at height.",
      candidates: [
        {
          id: "EMP-020",
          name: "Yuki Nakamura, CEng",
          location: "Japan",
          linkedin: "https://linkedin.com/in/yuki-nakamura-facade",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/YNakamura_CV.pdf",
          matchScore: 95,
          locked: false,
          skills: "16 years specializing in high-rise facade engineering and curtain wall systems. Chartered Engineer with expertise in unitized curtain wall design, structural silicone glazing, and double-skin facade systems. Experienced in wind-driven rain testing, thermal performance modeling, and facade maintenance access planning for supertall buildings.",
          pastProjects: ["Apex Tower – 68 Stories", "Meridian Supertall – New York", "Harbor Point Residential Tower"],
        },
      ],
    },
    {
      role: "Construction Manager",
      description: "Manages high-rise construction operations including vertical logistics, jump-form systems, and multi-trade coordination on a constrained urban site.",
      candidates: [
        {
          id: "EMP-006",
          name: "Frank O'Sullivan, CCM",
          location: "United States",
          linkedin: "https://linkedin.com/in/frank-osullivan",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/FOSullivan_CV.pdf",
          matchScore: 87,
          locked: false,
          skills: "22 years managing construction operations on infrastructure projects ranging from $50M to $800M. Certified Construction Manager (CCM) with expertise in CPM scheduling, earned value management, and lean construction principles.",
          pastProjects: ["Chesapeake Bay Bridge Rehabilitation", "I-405 Interchange Reconstruction", "Florida Turnpike Widening"],
        },
        {
          id: "EMP-021",
          name: "Brian Kwon, CCM",
          location: "South Korea",
          linkedin: "https://linkedin.com/in/brian-kwon-highrise",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/BKwon_CV.pdf",
          matchScore: 94,
          locked: false,
          skills: "17 years specializing in supertall and high-rise construction management. CCM-certified with deep expertise in jump-form and slip-form concrete systems, tower crane logistics, and vertical material distribution. Managed construction of five 50+ story buildings including two supertalls in Seoul and Singapore. Expert in constrained urban site logistics.",
          pastProjects: ["Apex Tower – 68 Stories", "Harbor Point Residential Tower", "One Pacific Place – Office Tower"],
        },
      ],
    },
    {
      role: "MEP Engineering Lead",
      description: "Coordinates the complex MEP systems across residential, office, hotel, and retail zones within the mixed-use tower.",
      candidates: [
        {
          id: "EMP-017",
          name: "Linda Chen-Williams, PE, CxA",
          location: "United States",
          linkedin: "https://linkedin.com/in/linda-chen-williams",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/LChenWilliams_CV.pdf",
          matchScore: 91,
          locked: false,
          skills: "20 years leading MEP design on large commercial, stadium, and convention center projects. Certified Commissioning Authority (CxA) and PE. Expert in large-venue HVAC systems, electrical distribution for events, and LEED-compliant mechanical design.",
          pastProjects: ["SolarDome Stadium – Phoenix", "National Convention Center – Denver", "Crown Hotel & Residences – Miami"],
        },
      ],
    },
    {
      role: "Vertical Transportation Consultant",
      description: "Designs the elevator and escalator systems for the supertall tower, including sky-lobby configurations and service logistics.",
      candidates: [
        {
          id: "EMP-022",
          name: "Raj Patel, MSc",
          location: "India",
          linkedin: "https://linkedin.com/in/raj-patel-vt",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/RPatel_CV.pdf",
          matchScore: 93,
          locked: false,
          skills: "14 years as a vertical transportation consultant specializing in supertall and ultra-high-rise buildings. Expert in destination dispatch elevator systems, double-deck elevator configurations, and sky-lobby transfer designs. Proficient in elevator traffic simulation (ELEVATE software) and has designed VT systems for eight buildings over 50 stories.",
          pastProjects: ["Apex Tower – 68 Stories", "Meridian Supertall – New York", "Crown Hotel & Residences – Miami"],
        },
      ],
    },
    {
      role: "Geotechnical Engineer",
      description: "Manages deep foundation design, excavation support systems, and dewatering for the 6-level underground parking structure.",
      candidates: [
        {
          id: "EMP-008",
          name: "Dr. Samuel Osei, PhD, PE",
          location: "Ghana",
          linkedin: "https://linkedin.com/in/samuel-osei-geotech",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/SOsei_CV.pdf",
          matchScore: 92,
          locked: false,
          skills: "Expert geotechnical engineer with 19 years specializing in deep foundation design, marine geotechnics, and ground improvement techniques. PhD in Geotechnical Engineering from MIT. Proficient in PLAXIS 3D, GeoStudio, and LPILE.",
          pastProjects: ["Port of Long Beach Access Bridge", "Chesapeake Bay Bridge Rehabilitation", "Apex Tower – 68 Stories"],
        },
      ],
    },
    {
      role: "Cost Estimator / Quantity Surveyor",
      description: "Develops detailed cost models for the mixed-use tower, manages procurement packages, and provides life-cycle cost analysis.",
      candidates: [
        {
          id: "EMP-011",
          name: "Trevor McAllister, CCP, MRICS",
          location: "Australia",
          linkedin: "https://linkedin.com/in/trevor-mcallister-qs",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/TMcAllister_CV.pdf",
          matchScore: 90,
          locked: false,
          skills: "21 years as a cost estimator and quantity surveyor on heavy civil and infrastructure projects. Certified Cost Professional (CCP) and MRICS-qualified. Expert in parametric and detailed bottom-up estimating, risk-adjusted contingency modeling, and earned value analysis (EVA).",
          pastProjects: ["I-5 Corridor Modernization", "Port of Long Beach Access Bridge", "SolarDome Stadium – Phoenix"],
        },
      ],
    },
  ],
  "PRJ-2026-004": [
    {
      role: "Program Director",
      description: "Provides strategic leadership across all phases of the $2.1B corridor expansion, manages DOT relationships, and oversees the multi-phase delivery program.",
      candidates: [
        {
          id: "EMP-001",
          name: "Richard Hargrove, PE, PMP",
          location: "United States",
          linkedin: "https://linkedin.com/in/richard-hargrove",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/RHargrove_CV.pdf",
          matchScore: 94,
          locked: false,
          skills: "30+ years leading large-scale infrastructure projects exceeding $500M. Expert in design-build delivery, stakeholder management, and regulatory compliance. Certified PMP and licensed PE in 12 states. Proven track record in bridge and marine construction with DOT agencies nationwide.",
          pastProjects: ["Chesapeake Bay Bridge Rehabilitation", "I-5 Corridor Modernization", "Hudson River Pedestrian Crossing"],
        },
      ],
    },
    {
      role: "Lead Highway Engineer",
      description: "Leads highway geometric design, pavement engineering, and interchange layout for the 180-mile corridor expansion.",
      candidates: [
        {
          id: "EMP-023",
          name: "Daniel Brooks, PE, PTOE",
          location: "United States",
          linkedin: "https://linkedin.com/in/daniel-brooks-highway",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/DBrooks_CV.pdf",
          matchScore: 96,
          locked: false,
          skills: "23 years in highway design and transportation engineering. Licensed PE and Professional Traffic Operations Engineer (PTOE). Expert in AASHTO geometric design, interchange modification reports (IMR), and pavement design using MEPDG. Proficient in MicroStation, OpenRoads, and Synchro traffic modeling. Led highway design on corridors totaling over 400 lane-miles.",
          pastProjects: ["I-5 Corridor Modernization", "Texas SH-130 Tollway Extension", "Florida Turnpike Widening"],
        },
      ],
    },
    {
      role: "Bridge Engineering Manager",
      description: "Manages the design and construction of 14 bridge replacements and 8 new interchange structures across the corridor.",
      candidates: [
        {
          id: "EMP-004",
          name: "Elena Vasquez, PE, MSc",
          location: "United States",
          linkedin: "https://linkedin.com/in/elena-vasquez-pe",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/EVasquez_CV.pdf",
          matchScore: 95,
          locked: false,
          skills: "18 years designing complex bridge structures including post-tensioned concrete, steel truss, and cable-stayed systems. Expert in AASHTO LRFD bridge design, construction-stage analysis, and accelerated bridge construction (ABC) techniques.",
          pastProjects: ["Hudson River Pedestrian Crossing", "I-75 Bridge Replacement Program", "Port of Long Beach Access Bridge"],
        },
      ],
    },
    {
      role: "Construction Manager",
      description: "Manages multi-phase construction operations across the 180-mile corridor while maintaining traffic flow and ensuring worker safety.",
      candidates: [
        {
          id: "EMP-006",
          name: "Frank O'Sullivan, CCM",
          location: "United States",
          linkedin: "https://linkedin.com/in/frank-osullivan",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/FOSullivan_CV.pdf",
          matchScore: 92,
          locked: false,
          skills: "22 years managing construction operations on infrastructure projects ranging from $50M to $800M. Certified Construction Manager (CCM) with expertise in CPM scheduling, earned value management, and lean construction principles.",
          pastProjects: ["Chesapeake Bay Bridge Rehabilitation", "I-405 Interchange Reconstruction", "Florida Turnpike Widening"],
        },
        {
          id: "EMP-007",
          name: "Priya Sharma, PMP",
          location: "India",
          linkedin: "https://linkedin.com/in/priya-sharma-cm",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/PSharma_CV.pdf",
          matchScore: 84,
          locked: false,
          skills: "16 years of construction management experience on large-scale bridge, highway, and tunnel projects. Strong capabilities in BIM coordination (Navisworks, Revit), 4D scheduling, and quality assurance/quality control (QA/QC).",
          pastProjects: ["Port of Long Beach Access Bridge", "Texas SH-130 Tollway Extension", "Hudson River Pedestrian Crossing"],
        },
      ],
    },
    {
      role: "Environmental Compliance Manager",
      description: "Manages environmental permits, ensures compliance across the 180-mile corridor, and coordinates with federal and state regulatory agencies.",
      candidates: [
        {
          id: "EMP-010",
          name: "Dr. Maria Santos, ENV SP",
          location: "Brazil",
          linkedin: "https://linkedin.com/in/maria-santos-env",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/MSantos_CV.pdf",
          matchScore: 93,
          locked: false,
          skills: "17 years in environmental compliance and sustainability for major infrastructure projects. Envision Sustainability Professional (ENV SP) with expertise in NEPA/CEQA compliance, wetland mitigation, endangered species management, and stormwater pollution prevention (SWPPP).",
          pastProjects: ["Chesapeake Bay Bridge Rehabilitation", "Hudson River Pedestrian Crossing", "I-5 Corridor Modernization"],
        },
      ],
    },
    {
      role: "ITS / Technology Lead",
      description: "Designs and oversees implementation of intelligent transportation systems including dynamic message signs, ramp metering, and traffic management centers.",
      candidates: [
        {
          id: "EMP-024",
          name: "Soo-Jin Park, PTOE, PMP",
          location: "South Korea",
          linkedin: "https://linkedin.com/in/soojin-park-its",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/SJPark_CV.pdf",
          matchScore: 94,
          locked: false,
          skills: "13 years specializing in intelligent transportation systems (ITS) and smart highway infrastructure. PTOE and PMP certified. Expert in connected vehicle technology, adaptive signal control (SCATS/SCOOT), fiber optic communication networks, and traffic management center (TMC) design. Led ITS deployments on corridors spanning over 500 miles across three states.",
          pastProjects: ["I-5 Corridor Modernization", "Texas SH-130 Tollway Extension", "Florida Turnpike Widening"],
        },
      ],
    },
    {
      role: "Lead Scheduler / Planning Engineer",
      description: "Develops the master program schedule for the multi-phase corridor expansion, coordinates phase transitions, and manages schedule risk across all work packages.",
      candidates: [
        {
          id: "EMP-013",
          name: "Jean-Pierre Moreau, PSP",
          location: "France",
          linkedin: "https://linkedin.com/in/jp-moreau-planning",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/JPMoreau_CV.pdf",
          matchScore: 95,
          locked: false,
          skills: "16 years as a planning and scheduling specialist on mega-projects valued up to $2B. Planning & Scheduling Professional (PSP) certified by AACE. Expert in Primavera P6, schedule risk analysis (SRA) using @RISK, and forensic delay analysis.",
          pastProjects: ["I-5 Corridor Modernization", "Texas SH-130 Tollway Extension", "Mississippi River Rail Bridge Upgrade"],
        },
      ],
    },
    {
      role: "Health & Safety Director",
      description: "Establishes and enforces site-wide HSE programs across multiple active construction zones spanning 180 miles of highway corridor.",
      candidates: [
        {
          id: "EMP-012",
          name: "Karen Whitfield, CSP, CHST",
          location: "United States",
          linkedin: "https://linkedin.com/in/karen-whitfield-safety",
          resumeUrl: "https://contoso.sharepoint.com/sites/HR/Resumes/KWhitfield_CV.pdf",
          matchScore: 93,
          locked: false,
          skills: "18 years directing safety programs on major construction projects with a career EMR of 0.68. Certified Safety Professional (CSP) and Construction Health & Safety Technician (CHST). Expert in behavior-based safety (BBS), fall protection planning, confined space rescue, and highway work zone safety.",
          pastProjects: ["Chesapeake Bay Bridge Rehabilitation", "I-405 Interchange Reconstruction", "Hudson River Pedestrian Crossing"],
        },
      ],
    },
  ],
};

// ============================================================================
// Contact Directory — Phone, Email, Teams
// ============================================================================

const contactInfo = {
  "EMP-001": { phone: "+1 (312) 555-0147", email: "richard.hargrove@contoso.com", teamsId: "richard.hargrove@contoso.com" },
  "EMP-002": { phone: "+1 (604) 555-0233", email: "catherine.dupont@contoso.com", teamsId: "catherine.dupont@contoso.com" },
  "EMP-003": { phone: "+81 3-5555-0891", email: "akira.tanaka@contoso.com", teamsId: "akira.tanaka@contoso.com" },
  "EMP-004": { phone: "+1 (415) 555-0364", email: "elena.vasquez@contoso.com", teamsId: "elena.vasquez@contoso.com" },
  "EMP-005": { phone: "+44 20 7555 0472", email: "marcus.webb@contoso.com", teamsId: "marcus.webb@contoso.com" },
  "EMP-006": { phone: "+1 (617) 555-0518", email: "frank.osullivan@contoso.com", teamsId: "frank.osullivan@contoso.com" },
  "EMP-007": { phone: "+91 22 5555 0629", email: "priya.sharma@contoso.com", teamsId: "priya.sharma@contoso.com" },
  "EMP-008": { phone: "+233 30 555 0741", email: "samuel.osei@contoso.com", teamsId: "samuel.osei@contoso.com" },
  "EMP-009": { phone: "+46 8 555 0853", email: "hannah.johansson@contoso.com", teamsId: "hannah.johansson@contoso.com" },
  "EMP-010": { phone: "+55 11 5555-0962", email: "maria.santos@contoso.com", teamsId: "maria.santos@contoso.com" },
  "EMP-011": { phone: "+61 2 5555 1074", email: "trevor.mcallister@contoso.com", teamsId: "trevor.mcallister@contoso.com" },
  "EMP-012": { phone: "+1 (713) 555-1185", email: "karen.whitfield@contoso.com", teamsId: "karen.whitfield@contoso.com" },
  "EMP-013": { phone: "+33 1 55 55 12 96", email: "jp.moreau@contoso.com", teamsId: "jp.moreau@contoso.com" },
  "EMP-014": { phone: "+1 (512) 555-1307", email: "william.torres@contoso.com", teamsId: "william.torres@contoso.com" },
  "EMP-015": { phone: "+39 02 5555 1418", email: "isabella.romano@contoso.com", teamsId: "isabella.romano@contoso.com" },
  "EMP-016": { phone: "+971 4 555 1529", email: "omar.alrashid@contoso.com", teamsId: "omar.alrashid@contoso.com" },
  "EMP-017": { phone: "+1 (206) 555-1630", email: "linda.chenwilliams@contoso.com", teamsId: "linda.chenwilliams@contoso.com" },
  "EMP-018": { phone: "+52 55 5555 1741", email: "carlos.mendoza@contoso.com", teamsId: "carlos.mendoza@contoso.com" },
  "EMP-019": { phone: "+49 30 5555 1852", email: "annika.berg@contoso.com", teamsId: "annika.berg@contoso.com" },
  "EMP-020": { phone: "+81 3-5555-1963", email: "yuki.nakamura@contoso.com", teamsId: "yuki.nakamura@contoso.com" },
  "EMP-021": { phone: "+82 2 5555 2074", email: "brian.kwon@contoso.com", teamsId: "brian.kwon@contoso.com" },
  "EMP-022": { phone: "+91 80 5555 2185", email: "raj.patel@contoso.com", teamsId: "raj.patel@contoso.com" },
  "EMP-023": { phone: "+1 (503) 555-2296", email: "daniel.brooks@contoso.com", teamsId: "daniel.brooks@contoso.com" },
  "EMP-024": { phone: "+82 2 5555 2307", email: "soojin.park@contoso.com", teamsId: "soojin.park@contoso.com" },
};

module.exports = { projects, staffingRoles, contactInfo };
