// Encrypts the private cost-rate benchmark values into src/encryptedRates.ts
// so the deployed bundle never contains plaintext numbers.
//
// Reads:  ../.private/original-cost-rates.json  (git-ignored, never deployed)
// Writes: src/encryptedRates.ts                 (base64 salt/iv/ciphertext)
//
// Usage:  RATES_PASSPHRASE=<passphrase> node scripts/encrypt-rates.mjs
//         (falls back to the value baked below if env var missing)
//
// Crypto: PBKDF2-SHA256 (100 000 iters, 16-byte salt) → 256-bit AES-GCM key
//         12-byte IV; ciphertext output is `enc || authTag` to match the
//         browser Web Crypto AES-GCM contract exactly.

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const appRoot = path.resolve(__dirname, '..');
const workspaceRoot = path.resolve(appRoot, '..');

const passphrase = process.env.RATES_PASSPHRASE || 'kiergroup2026$';
const inputPath = path.join(workspaceRoot, '.private', 'original-cost-rates.json');
const outputPath = path.join(appRoot, 'src', 'encryptedRates.ts');

if (!fs.existsSync(inputPath)) {
  console.error(`[encrypt-rates] Missing private source file: ${inputPath}`);
  process.exit(1);
}

const raw = fs.readFileSync(inputPath, 'utf8');
const data = JSON.parse(raw);
if (!Array.isArray(data.outputRates) || !Array.isArray(data.onCostComponents) || !Array.isArray(data.quarterlyIndices)) {
  console.error('[encrypt-rates] Expected "outputRates", "onCostComponents", "quarterlyIndices" arrays in JSON.');
  process.exit(1);
}

// Strip underscore-prefixed metadata keys; encrypt the rate bundle.
const bundle = Object.fromEntries(Object.entries(data).filter(([k]) => !k.startsWith('_')));
const plaintext = JSON.stringify(bundle);

const salt = crypto.randomBytes(16);
const iv = crypto.randomBytes(12);
const key = crypto.pbkdf2Sync(passphrase, salt, 100_000, 32, 'sha256');

const cipher = crypto.createCipheriv('aes-256-gcm', key, iv);
const enc = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
const authTag = cipher.getAuthTag();
const ciphertext = Buffer.concat([enc, authTag]);

const out = `// AUTO-GENERATED by scripts/encrypt-rates.mjs. DO NOT EDIT.
// Real cost-rate values are AES-GCM encrypted at build time from
// ../.private/original-cost-rates.json. Decryption happens in the browser
// when the user supplies the correct passphrase (see model.ts::unlockRates).
export const ENCRYPTED_RATES = {
  salt: '${salt.toString('base64')}',
  iv: '${iv.toString('base64')}',
  ciphertext: '${ciphertext.toString('base64')}'
};
`;

fs.writeFileSync(outputPath, out, 'utf8');
console.log(`[encrypt-rates] Wrote ${outputPath} (${ciphertext.length} bytes ciphertext).`);
